---
output: 
  prettydoc::html_pretty:
    theme: tactile
---
```{r child="header.md"}
```
<!-- Edit below this line. -->

# Getting ready for your workshop

Please take a bit of time to prepare for the workshop. When you have done what you can, please fill in [this very short form](https://docs.google.com/forms/d/e/1FAIpQLSdstrq-53AUCYWCGRV__9e8LS7xq2dws00RpCywAhSqCIlClQ/viewform?usp=sf_link).

## Intellectual thread

Think about the intro statistics course that you teach now or expect to teach.

* What do you teach students about handling data? (That is, not about the analysis of data but about how data is stored, accessed, transformed?)
* Which topics do you find unsatisfying? (This could be because you just don't like them, because students don't succeed in mastering the topic, or because they make no sense/don't fit in.)
* Which lesson have you been aching to improve?
* Hypothetical: Suppose you were tasked to develop a version of your statistics course that is only 2/3 as long as your current course. Which topics would you drop or consolidate? (Don't worry, you won't be asked to do this. We merely want to prompt you to prioritize the topics in your course.)
* What data sets do you currently use that you would like to give a higher profile?
* Are there data sets that you'd like to incorporate but haven't had a chance to do so?

Please write some notes about these questions (even if very brief), print them, and **bring them to the workshop**. Including your name is optional.

## Technical thread

You'll want to have a laptop or tablet computer so that you can participate directly in the many hands-on activities in the workshop. Whatever kind of machine it is, it should have three basic capabilities:

* A browser, e.g. Chrome or Safari or Firefox or IE
* Wifi to connect to the Internet
* A keyboard. Laptops, of course, have a keyboard built in. If you're using a tablet, having a separate keyboard makes it so much easier to use for the hands-on activities.

Depending on the workshop site, we may have a few computers on site for those participants who cannot bring their own. Contact the hub leader for your workshop for information. And even if you can't bring a computer, you'll be able to partner with your neighbor at the workshop.

## Sign up for cloud services

You don't need to install any special software on your own computer. Instead, we'll use services in the cloud that work through a standard web browser.

It's helpful if you set up a personal account on the cloud services listed below. That will save time on the day of the workshop and you can be a resource for your neighbor if they haven't had a chance to do so. (Do remember to keep track of your user ID and password. Writing it down is a good idea; you can chance the password after the workshop if you are worried about security.)

### 1. Google

You may already have a Google account: many people have an account already or work at an institution that provides email and other services through Google. If so, you are all set.

If you don't already have an account, follow [this link to sign up](https://support.google.com/mail/answer/56256?hl=en).  

Setting up a Google account is entirely to streamline authentication to other services that we use with StatPREP. You do not need to change anything about your existing email service or how you use it.

### 2. GitHub

Funny name, huh? GitHub is a free service with tens of millions of users. It's most closely associated with software development, but our main use for it will be to give you a way easily to create a web page to give your classes access to whichever StatPREP tutorials, lessons, or Little Apps you choose to use with them.

Your institution may already provide you with a web site or a system such as Moodle or Blackboard that gives you a class-specific web page. If so, the point of setting up a GitHub account to use at the workshop is to make it easier for us to avoid having to figure out how to upload documents to a multiplicity of different web platforms.

In selecting your user ID for GitHub, keep in mind that the ID is something that will be visible to students. So, `ProfJones` or something of that kind is probably better than `Red_hot_pepper_dude`.

Follow [this link to GitHub's account creation page](https://github.com/). And *don't be intimidated* by the "Built for developers" label. 

Once you've set up your account, GitHub will email a confirmation letter. **Make sure to click the confirm button** in the email.

### 3. RStudio cloud

We want you to have access to RStudio so that you can use it *if you decide you want to*. We'll show everyone some basics at the workshop so you can make an informed decision.

You can sign in using either your Google or your GitHub credentials; there's no need to set up a separate ID or password. Go to [`rstudio.cloud`](rstudio.cloud).

Remember to fill out the [very brief form](https://docs.google.com/forms/d/e/1FAIpQLSdstrq-53AUCYWCGRV__9e8LS7xq2dws00RpCywAhSqCIlClQ/viewform?usp=sf_link) summarizing your preparation.
