---
output: 
  prettydoc::html_pretty:
    theme: tactile
---
```{r child="header.md"}
```
<!-- Edit below this line. -->

# Resources

## Tutorials

* [StatPREP Tutorials](https://statprep.github.io/Workshops_2018/Tutorials/tutorials.html#Lessons). 

    These are intended primarily for *instructors*.
Topics include: 
R and data fundamentals, 
descriptive statistics and graphics, 
data wrangling, etc.

* Randy Pruim's ggformula-related tutorials

    * [Start with graphics](https://dtkaplan.shinyapps.io/Lesson_first_day_births/): Randy Pruim's first-day-of-class activity using Births in 2015 to introduce visual displays of data
    * [Tutorial: Less Volume, More Creativity](http://rstudio.calvin.edu:3939/ecots2018/) from eCOTS 2018 (includes material on ggformula)
    * [Tutorial: Intro to ggformula](http://rstudio.calvin.edu:3939/ggformula/intro/)
    * [Tutorial: Refining plots in ggformula](http://rstudio.calvin.edu:3939/ggformula/refining/)
        
* Data Wrangling with the `tidyverse` (`dplyr`, `tidyr`, etc.)

    * [Tutorial from a workshop at City of Hope](http://rstudio.calvin.edu:3939/tidyverse/city-of-hope-2018/)
    
## Little Apps

* [Little Apps](http://remodeling.danielkaplan.org/post/little-apps-for-teaching-stats/).

* [Revised Little Apps](https://statprep.github.io/Workshops_2018/LittleApps/little_apps.html) coming soon


## Other apps

Several other authors have statistics based apps, e.g.

* [power](http://www.rossmanchance.com/applets/power.html)

## Notes

* [Instructor notes for StatPREP technologies](http://StatPREP.github.io/InstructorNotes)

* [Amelia Macnamara's notes on R](HartfordLessons/Amiliaspresentation.pdf)

* [Statistic for Data Science](https://dtkaplan.github.io/SDS/) by D T Kaplan
    * [Data and Statistical Graphics Chapter](https://dtkaplan.github.io/SDS/data-statistical-graphics.html)

## Course Materials

These are materials that you might be able to use (perhaps after some
modification) when preparing your own courses.

* [Lessons for use in class](https://statprep.github.io/Workshops_2018/Lessons/lessons.html)

* You Want to Know exam problems from R Pruim: 
[[test 1](Resources/YouWantToKnow-test1.pdf)]
[[test 2](Resources/YouWantToKnow-test2.pdf)]
[[final](Resources/YouWantToKnow-final.pdf)]

## Textbooks

* The [Open Intro Stats](https://www.openintro.org/stat/textbook.php) books. There are three books in different styles:

    * Open Intro Statistics
    * Open Intro Stats with Simulation and Randomization
    * Advanced High-School Statistics
    
    The Open Intro books are available free on line and in print form for less than $10. We're going to use them as a source for examples in the tutorials and to illustrate "typical" textbook problems. 
    
* The very early stages of a textbook, [*Statistics for Data Science*](https://dtkaplan.github.io/SDS), being written by Danny Kaplan. An outline and explanation is published in [*The American Statistician*](https://peerj.com/preprints/3205.pdf)
    
## Professional Guidelines

* The [GAISE college report](http://www.amstat.org/asa/files/pdfs/GAISE/GaiseCollege_Full.pdf)
* The [ASA statement on p-values](https://www.amstat.org/asa/News/ASA-P-Value-Statement-Viewed-150000-Times.aspx)

## Of potential interest

* [Dance of the p-values](https://www.youtube.com/watch?v=5OL1RqHrZQ8)
