---
output: 
  prettydoc::html_pretty:
    theme: tactile
---

```{r child="header.md"}
```

# Schedule of Workshop Activities

This schedule is intended to be the hub from which you can access notes and activities for the StatPREP 2018 workshops. You might want to bookmark it in your browser so that you can find it quickly.

## Archive for workshops already held

Since the schedule evolves a bit from one workshop location to another, we're archiving the schedule as it was at the end of each workshop. 

* [Hartford, CT (June 1/2, 2018)](hartford_schedule.html)
* Saint Paul, MN (June 8/9, 2018) workshop coming up!

Note the [HELP!!](help_for_shy_people.html) menu item above. Use it if you're too shy to ask a question out loud. Also use it to help the StatPREP organizers by posting comments, criticisms, suggestions, and such. 

--------------------


## Schedule for Saint Kate's workshop

## Friday

4:00 pm Start

1. Welcome[.](Greetings_slides/cars_and_stats.html)

2. Examples of in-class lessons centered on data
    - Two-sample t [*Little App*](https://dtkaplan.shinyapps.io/LittleApp-t2/)
    - Concept lesson: What's normal? [Background](http://statprep.org/lesson-whats-normal/) and [activity](https://dtkaplan.shinyapps.io/Whats_normal)
    - On your own ... Start with graphics: Randy Pruim's first-day-of-class activity [tutorial](https://dtkaplan.shinyapps.io/Lesson_first_day_births/) and [notes on plotting](http://dtkaplan.shinyapps.io/Plotting_with_formulas)

3. Tidy data
    - [Notes](https://dtkaplan.github.io/SDS/tidy-data.html#May-16-2018-exer-4) and some group activities [one](https://dtkaplan.github.io/SDS/tidy-data.html#May-16-2018-exer-2), [two](https://dtkaplan.github.io/SDS/tidy-data.html#May-16-2018-exer-4)

4. Data and statistical graphics: The graphics behind the Little Apps.
    - [Tutorial](https://dtkaplan.shinyapps.io/Tutorial_data_and_Statistical_Graphics/)
    - [Notes](https://dtkaplan.github.io/SDS/data-statistical-graphics.html)

    - [Chapter from Statistics for Data Science by Danny Kaplan](https://dtkaplan.github.io/SDS/data-statistical-graphics.html)

    - [Tutorial Summary]()
    
6:00 pm Dinner at 6 pm 

5. Thinking about lessons. Select three topics from your current stats course that you would like to teach with data. They could be, for example, a technique, theory, or a project. 
    - Working with local data
    - Working with [Little Apps](LittleApps/little_app.html)
    
6. Learning R: Two tracks
    - Starting R: [functions](http://dtkaplan.shinyapps.io/Functions), [formulas](http://dtkaplan.shinyapps.io/Formulas), and parts of speech [notes](http://gifted-saha-3345d3.netlify.com/post/reading-r/) and [quiz](https://dtkaplan.shinyapps.io/part-of-speech-quiz/) and continue on with  [Tidy data frames](https://dtkaplan.shinyapps.io/Data_tables/), [Graphics for data science](https://dtkaplan.shinyapps.io/tutorial_data_science_graphics), [Calculating statistics](https://dtkaplan.shinyapps.io/Tutorial_Calculating_statistics/)
    - Using RStudio.cloud

8:00 pm Adjourn

## Saturday

1. Exploring statistics using tutorials: a [collection of choices](https://statprep.github.io/Workshops_2018/Tutorials/tutorials.html)

2. Statistical concepts: Two tracks:
    - Streamlining inference with regression
        - Little app on [regression](https://dtkaplan.shinyapps.io/littleapp-smoothing/), [proportions](https://dtkaplan.shinyapps.io/littleapp-proportions/), [one-way ANOVA](https://dtkaplan.shinyapps.io/littleapp-ANOVA-1/)
        - [R tutorial](https://dtkaplan.shinyapps.io/Tutorial_its_all_regression/)
    - Simulation-based inference:
        - Little apps involving resampling: [confidence intervals](https://dtkaplan.shinyapps.io/littleapp-generate-resamples/) & [proportions](https://dtkaplan.shinyapps.io/littleapp-proportions/)
        - R tutorials: [sampling](http://dtkaplan.shinyapps.io/Tutorial_sampling), [resampling](http://dtkaplan.shinyapps.io/Tutorial_resampling), and [shuffling](https://dtkaplan.shinyapps.io/Tutorial_permutation_test/)
    
3. Communicating with your students: Three tracks
    - [Setting up a course web site.](https://statprep.github.io/InstructorNotes/your-course-web-site.html)
    - Writing a `learnr` tutorial.
    - Collecting data with your students
        - [Globe tossing](https://dtkaplan.shinyapps.io/Tutorial_Globe_toss/#section-how-big-is-africa-versus-asia)
        - [Hypothesis testing with shuffling](http://dtkaplan.shinyapps.io/Tutorial_Riverboat_shuffle)
        
4. Determining lesson-development groups
    
5. Lesson development: Small group activity with two tracks
    - Developing lessons based on [Little Apps](http://remodeling.danielkaplan.org/post/little-apps-for-teaching-stats/)
    - Developing lessons using R commands.
    
6. Brief presentations of lessons developed
    - Hartford
        - [Data from the island](https://docs.google.com/document/d/1HMSh8hl6ImGAIzMuWwmq2600zbJb3DQjCw-qcKuTAQc/edit?usp=sharing)
        - [Post-it Notes](HartfordLessons/posted_notes.Rmd)
        - Hartford Corrections data in [HTML](HartfordLessons/correctionsdata.html) and [Rmd](HartfordLessons/correctionsdata.Rmd) and the [data set](HartfordLessons/Correctional_Facility_Daily_Population_Count_By_Facility.csv) ... or the [rstudio.cloud project](https://rstudio.cloud/project/39333)
    - St. Paul

7. Evaluation: Help us improve!

8. Going forward ... support and staying in touch

### Explanation

This schedule does not include information about specific timing, breaks, meals, and such. That's because each of the four workshop locations will have slightly different arrangements with respect to those things.

You'll notice that there are three distinct styles of interaction planned for the workshop:

1. Presentations and discussions that are in the style of a class you might teach your own students, but with the workshop participants playing the role of the students.
2. Activities where the participants are preparing lessons for use in their own classrooms.
3. Training and work as data scientists undertaking analysis of data.


