---
output: 
  prettydoc::html_pretty:
    theme: tactile
---

```{r child="header.md"}
```


## Schedule for Highline College workshop (Seattle) June 15-16

## Friday

8:30 am, breakfast

9:00 am, start program

1. Welcome[.](Greetings_slides/cars_and_stats.html)

2. Examples of in-class lessons centered on data
    - Two-sample t [*Little App*](https://dtkaplan.shinyapps.io/LittleApp-t2/)
    - Concept lesson: What's normal? [Background](http://statprep.org/lesson-whats-normal/) and [activity](https://dtkaplan.shinyapps.io/Whats_normal)
    - [Start with graphics](https://dtkaplan.shinyapps.io/Lesson_first_day_births/): Randy Pruim's ~~first~~ second-day-of-class activity using Births in 2015 to introduce visual displays of data
        * [Tutorial: Less Volume, More Creativity](http://rstudio.calvin.edu:3939/ecots2018/) from eCOTS 2018 (includes material on ggformula)
        * [Tutorial: Intro to ggformula](http://rstudio.calvin.edu:3939/ggformula/intro/)
        * [Tutorial: Refining plots in ggformula](http://rstudio.calvin.edu:3939/ggformula/refining/)
        * [Danny's notes on plotting](http://dtkaplan.shinyapps.io/Plotting_with_formulas)
    

3. Tidy data
    - [Notes](https://dtkaplan.github.io/SDS/tidy-data.html#May-16-2018-exer-4) and [group activity](https://docs.google.com/spreadsheets/d/1Ow6Cm4z-Z1Yybk3i352msulYCEDOUaOghmo9ALajyHo/edit?usp=sharing) <!-- [one](https://dtkaplan.github.io/SDS/tidy-data.html#May-16-2018-exer-2), [two](https://dtkaplan.github.io/SDS/tidy-data.html#May-16-2018-exer-4) -->
    

4. Data and statistical graphics: The graphics behind the Little Apps.
    - [Tutorial summary](https://dtkaplan.shinyapps.io/Tutorial_data_and_Statistical_Graphics/)
    - [Chapter from *Statistics for Data Science* by Danny Kaplan](https://dtkaplan.github.io/SDS/data-statistical-graphics.html)
    
12:30 pm Lunch

5. Thinking about lessons. Select three topics from your current stats course that you would like to teach with data. They could be, for example, a technique, theory, or a project. 
    - Working with local data
    - Working with [Little Apps](LittleApps/little_app.html)
    
6. Learning R: Two tracks
    - Starting R: [functions](http://dtkaplan.shinyapps.io/Functions), [formulas](http://dtkaplan.shinyapps.io/Formulas), and parts of speech [notes](http://gifted-saha-3345d3.netlify.com/post/reading-r/) and [quiz](https://dtkaplan.shinyapps.io/part-of-speech-quiz/) and continue on with  [tidy data frames](https://dtkaplan.shinyapps.io/Data_tables/), [graphics for data science](https://dtkaplan.shinyapps.io/tutorial_data_science_graphics), [calculating statistics](https://dtkaplan.shinyapps.io/Tutorial_Calculating_statistics/)
    - Using RStudio.cloud
    
7. Exploring statistics using StatPREP materials.
    - [Tutorials](https://statprep.github.io/Workshops_2018/Tutorials/tutorials.html), which are instructor-oriented, R-based introductions to techniques and concepts.
    - [Little Apps](https://statprep.github.io/Workshops_2018/LittleApps/little_apps.html)


3:15 pm Adjourn

## Saturday

8:30 am, breakfast

9:00 am, start program

1. Statistical concepts: Two tracks:
    - Streamlining inference with regression
        - Little app on [regression](https://dtkaplan.shinyapps.io/littleapp-smoothing/), [proportions](https://dtkaplan.shinyapps.io/littleapp-proportions/), [one-way ANOVA](https://dtkaplan.shinyapps.io/littleapp-ANOVA-1/)
        - [R tutorial](https://dtkaplan.shinyapps.io/Tutorial_its_all_regression/)
    - Simulation-based inference:
        - Little apps involving resampling: [confidence intervals](https://dtkaplan.shinyapps.io/littleapp-generate-resamples/) & [proportions](https://dtkaplan.shinyapps.io/littleapp-proportions/)
        - R tutorials: [sampling](http://dtkaplan.shinyapps.io/Tutorial_sampling), [resampling](http://dtkaplan.shinyapps.io/Tutorial_resampling), and [shuffling](https://dtkaplan.shinyapps.io/Tutorial_permutation_test/)
    
2. Communicating with your students: Three tracks
    - [Setting up a course web site.](https://statprep.github.io/InstructorNotes/your-course-web-site.html)
    - Writing a `learnr` tutorial.
        - [Tutorial on `df_stats()`](http://rsconnect.calvin.edu:3939/dfstats-MSP-StatPREP/)
        - [Code for the tutorial](Creating-Tutorials/StatPREP-demo/StatPREP-demo.Rmd)
    - Collecting data with your students
        - [Globe tossing](https://dtkaplan.shinyapps.io/Tutorial_Globe_toss/#section-how-big-is-africa-versus-asia)
        - [Hypothesis testing with shuffling](http://dtkaplan.shinyapps.io/Tutorial_Riverboat_shuffle)
        
3. Determining lesson-development groups. [Homework answers](homework.html)

12:30 pm Lunch

    
4. Lesson development: Small group activity with two tracks
    - Developing lessons based on [Little Apps](http://remodeling.danielkaplan.org/post/little-apps-for-teaching-stats/)
    - Developing lessons using R commands.
    
5. Brief presentations of lessons developed
    - Hartford
        - [Data from the island](https://docs.google.com/document/d/1HMSh8hl6ImGAIzMuWwmq2600zbJb3DQjCw-qcKuTAQc/edit?usp=sharing)
        - [Post-it Notes](HartfordLessons/posted_notes.Rmd)
        - Hartford Corrections data in [HTML](HartfordLessons/correctionsdata.html) and [Rmd](HartfordLessons/correctionsdata.Rmd) and the [data set](HartfordLessons/Correctional_Facility_Daily_Population_Count_By_Facility.csv) ... or the [rstudio.cloud project](https://rstudio.cloud/project/39333)
    - St. Paul
        - Support for investment in Saint Paul parks
        - Bayesian analysis
        - [Joining data to make maps](StPaulRecSurvey/ParksAndRecSurvey.html)

6. Going forward ... support and staying in touch

3:15 pm, adjourn



